version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    groups:
      go-development:
        dependency-type: development
        patterns:
          - "*"
    ignore:
      - dependency-name: github.com/charmbracelet/x/vt
      - dependency-name: github.com/charmbracelet/ultraviolet
