package config

import "time"

const CurrentVersion = 2

func DefaultConfig() *Config {
	return &Config{
		Core: CoreConfig{
			Version: CurrentVersion,
			Shell:   "",
			Mode:    "last",
			Debug:   false,
		},
		UI: UIConfig{
			Style:          "modern",
			PromptPosition: "classic",
			Density:        "balanced",
			Responsive:     true,
			Palette:        "auto",
			Contrast:       "normal",
			ColorVision:    "default",
			GhostText:      true,
			MaxSuggestions: 100,
			MaxHeight:      15,
			NerdFonts:      true,
			History:        HistoryUIConfig{},
			Chatbox: ChatboxConfig{
				Prompt:            "› ",
				Separator:         " · ",
				Scrollback:        "output",
				PathColorMode:     "hierarchy",
				PathMaxSegments:   6,
				HistorySpacing:    1,
				TitleLeft:         []string{"directory"},
				TitleRight:        []string{"package", "versions"},
				StatusLeft:        []string{"session", "git-branch", "git-status", "git-added", "git-deleted", "git-stash", "git-lines", "environment", "version-mismatch", "contexts", "stale"},
				StatusRight:       []string{"jobs", "duration", "exit", "cpu", "memory"},
				RefreshInterval:   Duration(time.Second),
				CollapseVersions:  true,
				SnapshotMetadata:  "changed",
				CompletedCommand:  "outcome",
				Metrics:           "always",
				Versions:          "auto",
				DockerContext:     "auto",
				KubernetesContext: "auto",
				AWSContext:        "auto",
				DurationFast:      Duration(500 * time.Millisecond),
				DurationSlow:      Duration(2 * time.Second),
				CPUAverage:        50,
				CPUHigh:           75,
				CPUCritical:       90,
				MemoryAverage:     50,
				MemoryHigh:        75,
				MemoryCritical:    90,
				Colors: ChatboxColorsConfig{
					Directory: "#61ffcf", DirectoryRoot: "#739ee8", DirectoryReadOnly: "#ff7b72",
					GitBranch: "#fd7df4", GitStatus: "#f3c969",
					GitClean: "#61ffcf", GitOperation: "#fd7df4", GitConflicts: "#ff7b72",
					GitStaged: "#61ffcf", GitModified: "#f3c969", GitRenamed: "#739ee8", GitUntracked: "#caa472",
					GitAhead: "#00add8", GitBehind: "#ce422b",
					GitAdded: "#61ffcf", GitDeleted: "#ff7b72", GitStash: "#caa472",
					GitLinesAdded: "#61ffcf", GitLinesDeleted: "#ff7b72",
					Session: "#739ee8", SessionWarning: "#f3c969", SessionCritical: "#ff7b72",
					Contexts: "#2496ed", Environment: "#68a063", VersionMismatch: "#ff7b72",
					Package: "#caa472", Stale: "#f3c969", Jobs: "#739ee8", JobsStopped: "#f3c969",
					ExitNeutral: "#747579", ExitSuccess: "#61ffcf", ExitFailure: "#ff7b72", Duration: "#c6cad7",
					DurationFast: "#61ffcf", DurationAverage: "#f3c969", DurationSlow: "#ff7b72",
					LoadLow: "#61ffcf", LoadAverage: "#f3c969", LoadHigh: "#ce422b", LoadCritical: "#ff7b72",
					Laravel: "#ff2d20", PHP: "#777bb4", Composer: "#caa472",
					Python: "#3776ab", Ruby: "#cc342d", Elixir: "#6e4a7e",
					Go: "#00add8", Node: "#68a063", Bun: "#f6e8d5", Rust: "#ce422b",
					Docker: "#2496ed", DockerCompose: "#5b8def",
					CPU: "#c6cad7", Memory: "#c6cad7",
				},
			},
			Colors: ColorsConfig{
				Day: ColorPaletteConfig{
					Background:                 "#f8f5f1",
					Border:                     "#1d67f6",
					Accent:                     "#3c9339",
					Muted:                      "#747579",
					Text:                       "#242529",
					TextSelected:               "#242529",
					Match:                      "#084ccf",
					Description:                "#747579",
					DescriptionSelected:        "#242529",
					SelectionBackground:        "#dbe2f2",
					SurfaceBackground:          "#e9e4de",
					CompletedSurfaceBackground: "#f1ede8",
					StatusBackground:           "#f8f5f1",
					StatusText:                 "#242529",
					ScrollInfo:                 "#984ea5",
					GhostText:                  "#747579",
				},
				Night: ColorPaletteConfig{
					Background:                 "#080a0d",
					Border:                     "#739ee8",
					Accent:                     "#61ffcf",
					Muted:                      "#404658",
					Text:                       "#c6cad7",
					TextSelected:               "#ffffff",
					Match:                      "#61eeff",
					Description:                "#739ee8",
					DescriptionSelected:        "#c6cad7",
					SelectionBackground:        "#1a1e24",
					SurfaceBackground:          "#242528",
					CompletedSurfaceBackground: "#17191d",
					StatusBackground:           "#080a0d",
					StatusText:                 "#c6cad7",
					ScrollInfo:                 "#fd7df4",
					GhostText:                  "#404658",
				},
			},
		},
		Git: GitConfig{
			FilterActiveBranch:  true,
			DeduplicateBranches: true,
		},
		Updater: UpdaterConfig{
			CheckOnStartup: true,
			Channel:        "stable",
			CheckInterval:  Duration(24 * time.Hour),
		},
		AI: AIConfig{
			Enabled:       false,
			Provider:      "",
			DebounceMS:    500,
			MinIntervalMS: 1000,
			Providers:     nil,
			SuggestOnEmpty: SuggestOnEmptyConfig{
				Enabled:       false,
				DebounceMS:    800,
				MinIntervalMS: 5000,
			},
		},
		Suggestions: SuggestionsConfig{
			SuppressDestructive: true,
		},
		Keybindings: KeybindingsConfig{
			Keymap:             "emacs",
			HistorySearch:      "ctrl+r",
			HistorySuccessOnly: "ctrl+s",
			Accept:             "tab",
			ToggleOverlay:      "shift+tab",
			AcceptToken:        []string{"alt+right", "ctrl+right", "meta+right"},
		},
	}
}

func DefaultState() *State {
	return &State{
		LastMode: "spec",
		Updater: UpdaterState{
			LastCheckTime: time.Time{},
			SeenVersion:   "",
		},
	}
}
