package config

import (
	"bytes"
	"fmt"
	"os"
	"slices"
	"strings"

	"github.com/BurntSushi/toml"
)

var PresetNames = []string{"minimal", "balanced", "context-rich", "ops"}

func Preset(name string) (*Config, error) {
	cfg := DefaultConfig()
	cfg.UI.PromptPosition = "bottom"
	cfg.UI.Density = "balanced"
	cfg.UI.Responsive = true
	cfg.UI.Chatbox.Metrics = "when-high"

	switch name {
	case "minimal":
		cfg.UI.Density = "compact"
		cfg.UI.MaxSuggestions = 25
		cfg.UI.Chatbox.TitleRight = nil
		cfg.UI.Chatbox.StatusLeft = []string{"git-branch", "git-status"}
		cfg.UI.Chatbox.StatusRight = []string{"duration", "exit"}
		cfg.UI.Chatbox.Versions = "never"
		cfg.UI.Chatbox.Metrics = "never"
	case "balanced":
		cfg.UI.Chatbox.TitleRight = []string{"versions"}
		cfg.UI.Chatbox.StatusLeft = []string{"git-branch", "git-status", "environment", "version-mismatch"}
		cfg.UI.Chatbox.StatusRight = []string{"duration", "exit", "cpu", "memory"}
	case "context-rich":
		cfg.UI.Density = "rich"
		cfg.UI.Chatbox.Metrics = "always"
	case "ops":
		cfg.UI.Density = "rich"
		cfg.UI.Chatbox.TitleRight = []string{"versions"}
		cfg.UI.Chatbox.StatusLeft = []string{"session", "git-branch", "git-status", "contexts", "stale"}
		cfg.UI.Chatbox.StatusRight = []string{"jobs", "duration", "exit", "cpu", "memory"}
		cfg.UI.Chatbox.Metrics = "always"
		cfg.UI.Chatbox.DockerContext = "always"
		cfg.UI.Chatbox.KubernetesContext = "always"
		cfg.UI.Chatbox.AWSContext = "always"
	default:
		return nil, fmt.Errorf("unknown preset %q (want: %v)", name, PresetNames)
	}

	if err := validate(cfg); err != nil {
		return nil, err
	}
	return cfg, nil
}

func Render(cfg *Config) ([]byte, error) {
	var output bytes.Buffer
	output.WriteString("# ~/.config/vuja/config.toml\n# generated by vuja; edit any value and run `vuja config validate`\n\n")
	if err := toml.NewEncoder(&output).Encode(cfg); err != nil {
		return nil, err
	}
	return output.Bytes(), nil
}

func DefaultConfigContent() ([]byte, error) {
	cfg, err := Preset("balanced")
	if err != nil {
		return nil, err
	}
	return Render(cfg)
}

func LoadPath(path string) (*Config, error) {
	cfg := DefaultConfig()
	if err := RestrictPrivateFiles(path); err != nil {
		return cfg, err
	}
	data, err := os.ReadFile(path)
	if err != nil {
		return cfg, fmt.Errorf("config: read %s: %w", path, err)
	}
	metadata, err := toml.Decode(string(data), cfg)
	if err != nil {
		return cfg, fmt.Errorf("config: parse %s: %w", path, err)
	}
	if err := applyLegacyChatboxLayout(cfg, &metadata); err != nil {
		return cfg, fmt.Errorf("config: invalid value: %w", err)
	}
	applyLegacyChatboxColors(cfg, &metadata)
	applySchemaCompatibility(cfg, &metadata)
	if undecoded := metadata.Undecoded(); len(undecoded) > 0 {
		keys := make([]string, 0, len(undecoded))
		for _, key := range undecoded {
			keys = append(keys, key.String())
		}
		slices.Sort(keys)
		return cfg, fmt.Errorf("config: unknown keys: %s", strings.Join(keys, ", "))
	}
	if err := validate(cfg); err != nil {
		return cfg, fmt.Errorf("config: invalid value: %w", err)
	}
	return cfg, nil
}

func Validate(cfg *Config) error {
	return validate(cfg)
}

func VersionVisible(chatbox ChatboxConfig, provider string) bool {
	if chatbox.Versions == "never" || slices.Contains(chatbox.VersionDeny, provider) {
		return false
	}
	return len(chatbox.VersionAllow) == 0 || slices.Contains(chatbox.VersionAllow, provider)
}

func ApplyVisualPolicy(cfg *Config) {
	if cfg == nil {
		return
	}
	if cfg.UI.Palette == "terminal" {
		terminal := ColorPaletteConfig{
			Background: "0", Border: "4", Accent: "6", Muted: "8", Text: "7", TextSelected: "15",
			Match: "6", Description: "8", DescriptionSelected: "7", SelectionBackground: "8",
			SurfaceBackground: "8", CompletedSurfaceBackground: "0", StatusBackground: "0",
			StatusText: "7", ScrollInfo: "5", GhostText: "8",
		}
		cfg.UI.Colors.Day = terminal
		cfg.UI.Colors.Night = terminal
		terminalColors := map[string]string{
			"directory": "6", "directory-root": "4", "directory-read-only": "1",
			"git-branch": "5", "git-status": "3", "git-clean": "2", "git-operation": "5",
			"git-conflicts": "1", "git-staged": "2", "git-modified": "3", "git-renamed": "4",
			"git-untracked": "3", "git-ahead": "6", "git-behind": "1", "git-added": "2",
			"git-deleted": "1", "git-stash": "3", "git-lines-added": "2", "git-lines-deleted": "1",
			"session": "4", "session-warning": "3", "session-critical": "1", "contexts": "4",
			"environment": "2", "version-mismatch": "1", "package": "3", "stale": "3",
			"jobs": "4", "jobs-stopped": "3", "exit-neutral": "8", "exit-success": "2",
			"exit-failure": "1", "duration": "7", "duration-fast": "2", "duration-average": "3",
			"duration-slow": "1", "load-low": "2", "load-average": "3", "load-high": "1",
			"load-critical": "9", "laravel": "1", "php": "5", "composer": "3", "python": "4",
			"ruby": "1", "elixir": "5", "go": "6", "node": "2", "bun": "7", "rust": "1",
			"docker": "4", "docker-compose": "4", "cpu": "7", "memory": "7",
		}
		for name, target := range namedChatboxColorTargets(&cfg.UI.Chatbox.Colors) {
			if value := terminalColors[name]; value != "" {
				*target = value
			}
		}
	}
	if cfg.UI.Contrast == "high" {
		dayMuted, nightMuted := "#4a4b50", "#8f96a8"
		if cfg.UI.Palette == "terminal" {
			dayMuted, nightMuted = "7", "7"
		}
		cfg.UI.Colors.Day.Muted = dayMuted
		cfg.UI.Colors.Day.Description = dayMuted
		cfg.UI.Colors.Day.GhostText = dayMuted
		cfg.UI.Colors.Night.Muted = nightMuted
		cfg.UI.Colors.Night.Description = nightMuted
		cfg.UI.Colors.Night.GhostText = nightMuted
	}
	switch cfg.UI.ColorVision {
	case "deuteranopia":
		applyAccessibleSemanticColors(&cfg.UI.Chatbox.Colors, "#56b4e9", "#d55e00", "#e69f00")
	case "protanopia":
		applyAccessibleSemanticColors(&cfg.UI.Chatbox.Colors, "#0072b2", "#e69f00", "#f0e442")
	case "monochrome":
		base := cfg.UI.Colors.Night.Text
		colors := &cfg.UI.Chatbox.Colors
		for _, target := range chatboxColorTargets(colors) {
			*target = base
		}
	}
}

func applyAccessibleSemanticColors(colors *ChatboxColorsConfig, success, danger, warning string) {
	for _, target := range []*string{
		&colors.GitClean, &colors.GitStaged, &colors.GitAdded, &colors.GitLinesAdded,
		&colors.ExitSuccess, &colors.DurationFast, &colors.LoadLow,
	} {
		*target = success
	}
	for _, target := range []*string{
		&colors.DirectoryReadOnly, &colors.GitConflicts, &colors.GitBehind, &colors.GitDeleted,
		&colors.GitLinesDeleted, &colors.SessionCritical, &colors.VersionMismatch,
		&colors.ExitFailure, &colors.DurationSlow, &colors.LoadHigh, &colors.LoadCritical,
	} {
		*target = danger
	}
	for _, target := range []*string{
		&colors.GitStatus, &colors.GitModified, &colors.GitUntracked, &colors.GitStash,
		&colors.SessionWarning, &colors.Stale, &colors.JobsStopped,
		&colors.DurationAverage, &colors.LoadAverage,
	} {
		*target = warning
	}
}

func chatboxColorTargets(colors *ChatboxColorsConfig) []*string {
	return []*string{
		&colors.Directory, &colors.DirectoryRoot, &colors.DirectoryReadOnly,
		&colors.GitBranch, &colors.GitStatus, &colors.GitClean, &colors.GitOperation,
		&colors.GitConflicts, &colors.GitStaged, &colors.GitModified, &colors.GitRenamed,
		&colors.GitUntracked, &colors.GitAhead, &colors.GitBehind, &colors.GitAdded,
		&colors.GitDeleted, &colors.GitStash, &colors.GitLinesAdded, &colors.GitLinesDeleted,
		&colors.Session, &colors.SessionWarning, &colors.SessionCritical, &colors.Contexts,
		&colors.Environment, &colors.VersionMismatch, &colors.Package, &colors.Stale,
		&colors.Jobs, &colors.JobsStopped, &colors.ExitNeutral, &colors.ExitSuccess,
		&colors.ExitFailure, &colors.Duration, &colors.DurationFast, &colors.DurationAverage,
		&colors.DurationSlow, &colors.LoadLow, &colors.LoadAverage, &colors.LoadHigh,
		&colors.LoadCritical, &colors.Laravel, &colors.PHP, &colors.Composer, &colors.Python,
		&colors.Ruby, &colors.Elixir, &colors.Go, &colors.Node, &colors.Bun, &colors.Rust,
		&colors.Docker, &colors.DockerCompose, &colors.CPU, &colors.Memory,
	}
}

func namedChatboxColorTargets(colors *ChatboxColorsConfig) map[string]*string {
	names := []string{
		"directory", "directory-root", "directory-read-only", "git-branch", "git-status", "git-clean",
		"git-operation", "git-conflicts", "git-staged", "git-modified", "git-renamed", "git-untracked",
		"git-ahead", "git-behind", "git-added", "git-deleted", "git-stash", "git-lines-added",
		"git-lines-deleted", "session", "session-warning", "session-critical", "contexts", "environment",
		"version-mismatch", "package", "stale", "jobs", "jobs-stopped", "exit-neutral", "exit-success",
		"exit-failure", "duration", "duration-fast", "duration-average", "duration-slow", "load-low",
		"load-average", "load-high", "load-critical", "laravel", "php", "composer", "python", "ruby",
		"elixir", "go", "node", "bun", "rust", "docker", "docker-compose", "cpu", "memory",
	}
	targets := chatboxColorTargets(colors)
	result := make(map[string]*string, len(names))
	for index, name := range names {
		result[name] = targets[index]
	}
	return result
}
